language: csharp
dotnet: 2.1
os: windows
solution: SiemensMaritimeTool.sln
install:
  - nuget restore SiemensMaritimeTool.sln
  - nuget install xunit.runners -Version 2.4.1 -OutputDirectory testrunner
script:
    - dotnet test Schwartz.Siemens.Test.Core.cdproj
    - dotnet test Schwartz.Siemens.Test.Infrastructure.Data.cdproj
